# Generated by Django 4.2.7 on 2023-11-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_usermodel_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='phoneNo',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
